[workspace]
resolver = "3"

members = [
    "clash-bin",
    "clash-lib",
    "clash-common",
    "clash-doc",
    "clash-ffi",
    "clash-dns",
    "clash-netstack",
    "clash-ebpf",
    "clash-ebpf-common",
    "clash-shadowsocks"
]
exclude = ["clash-ebpf-bpf"]



[workspace.package]
version = "0.20.2-alpha"
repository = "https://github.com/CHKayanami/clash-rs"
edition = "2024"
authors = ["https://github.com/Watfaq/clash-rs/graphs/contributors"]
homepage = "https://github.com/CHKayanami/clash-rs"

[profile.release]
opt-level = 3
codegen-units = 1
lto = "fat"
strip = "symbols"
debug = 0
panic = "abort"


[profile.detailed-release]
inherits = "release"
opt-level = 1
lto = "thin"
strip = "none"
debug = "line-tables-only"
split-debuginfo = "off"
panic = "unwind"
incremental = true
codegen-units = 256

[profile.profiling]
inherits = "release"
debug = "line-tables-only"
strip = "none"
opt-level = "z"
lto = "fat"
codegen-units = 1

[workspace.lints.rust]
warnings = "deny"
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(docker_test)', 'cfg(throughput_test)', 'cfg(tokio_unstable)'] }

[workspace.lints.clippy]
redundant_clone = "deny"
needless_collect = "deny"

[patch.crates-io]
boring-sys = { git = "https://github.com/CHKayanami/boring-sys", rev = "04a1111ac32c694b97ed3cde70c56174bb90f028" }
